// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/xtls/rwstats/command.proto

package rwstats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the GetUsersStats extension shipped by @remnawave/xtls-sdk 0.16.0.
// The upstream xray-core Go module does not yet expose these generated types.
type OnlineIPEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineIPEntry) Reset() {
	*x = OnlineIPEntry{}
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineIPEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineIPEntry) ProtoMessage() {}

func (x *OnlineIPEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineIPEntry.ProtoReflect.Descriptor instead.
func (*OnlineIPEntry) Descriptor() ([]byte, []int) {
	return file_internal_xtls_rwstats_command_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineIPEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OnlineIPEntry) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type TrafficUserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uplink        int64                  `protobuf:"varint,1,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      int64                  `protobuf:"varint,2,opt,name=downlink,proto3" json:"downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficUserStat) Reset() {
	*x = TrafficUserStat{}
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficUserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficUserStat) ProtoMessage() {}

func (x *TrafficUserStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficUserStat.ProtoReflect.Descriptor instead.
func (*TrafficUserStat) Descriptor() ([]byte, []int) {
	return file_internal_xtls_rwstats_command_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficUserStat) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *TrafficUserStat) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

type UserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           []*OnlineIPEntry       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	Traffic       *TrafficUserStat       `protobuf:"bytes,3,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStat) Reset() {
	*x = UserStat{}
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStat) ProtoMessage() {}

func (x *UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStat.ProtoReflect.Descriptor instead.
func (*UserStat) Descriptor() ([]byte, []int) {
	return file_internal_xtls_rwstats_command_proto_rawDescGZIP(), []int{2}
}

func (x *UserStat) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserStat) GetIps() []*OnlineIPEntry {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *UserStat) GetTraffic() *TrafficUserStat {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type GetUsersStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeTraffic bool                   `protobuf:"varint,1,opt,name=include_traffic,json=includeTraffic,proto3" json:"include_traffic,omitempty"`
	Reset_         bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsersStatsRequest) Reset() {
	*x = GetUsersStatsRequest{}
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStatsRequest) ProtoMessage() {}

func (x *GetUsersStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_xtls_rwstats_command_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersStatsRequest) GetIncludeTraffic() bool {
	if x != nil {
		return x.IncludeTraffic
	}
	return false
}

func (x *GetUsersStatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type GetUsersStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStat            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersStatsResponse) Reset() {
	*x = GetUsersStatsResponse{}
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStatsResponse) ProtoMessage() {}

func (x *GetUsersStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xtls_rwstats_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_xtls_rwstats_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersStatsResponse) GetUsers() []*UserStat {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_internal_xtls_rwstats_command_proto protoreflect.FileDescriptor

const file_internal_xtls_rwstats_command_proto_rawDesc = "" +
	"\n" +
	"#internal/xtls/rwstats/command.proto\x12\x16xray.app.stats.command\"<\n" +
	"\rOnlineIPEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\"E\n" +
	"\x0fTrafficUserStat\x12\x16\n" +
	"\x06uplink\x18\x01 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x02 \x01(\x03R\bdownlink\"\x9c\x01\n" +
	"\bUserStat\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x127\n" +
	"\x03ips\x18\x02 \x03(\v2%.xray.app.stats.command.OnlineIPEntryR\x03ips\x12A\n" +
	"\atraffic\x18\x03 \x01(\v2'.xray.app.stats.command.TrafficUserStatR\atraffic\"U\n" +
	"\x14GetUsersStatsRequest\x12'\n" +
	"\x0finclude_traffic\x18\x01 \x01(\bR\x0eincludeTraffic\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"O\n" +
	"\x15GetUsersStatsResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .xray.app.stats.command.UserStatR\x05usersBAZ?github.com/Luxiaba/remnawave-node-lite-go/internal/xtls/rwstatsb\x06proto3"

var (
	file_internal_xtls_rwstats_command_proto_rawDescOnce sync.Once
	file_internal_xtls_rwstats_command_proto_rawDescData []byte
)

func file_internal_xtls_rwstats_command_proto_rawDescGZIP() []byte {
	file_internal_xtls_rwstats_command_proto_rawDescOnce.Do(func() {
		file_internal_xtls_rwstats_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_xtls_rwstats_command_proto_rawDesc), len(file_internal_xtls_rwstats_command_proto_rawDesc)))
	})
	return file_internal_xtls_rwstats_command_proto_rawDescData
}

var file_internal_xtls_rwstats_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_xtls_rwstats_command_proto_goTypes = []any{
	(*OnlineIPEntry)(nil),         // 0: xray.app.stats.command.OnlineIPEntry
	(*TrafficUserStat)(nil),       // 1: xray.app.stats.command.TrafficUserStat
	(*UserStat)(nil),              // 2: xray.app.stats.command.UserStat
	(*GetUsersStatsRequest)(nil),  // 3: xray.app.stats.command.GetUsersStatsRequest
	(*GetUsersStatsResponse)(nil), // 4: xray.app.stats.command.GetUsersStatsResponse
}
var file_internal_xtls_rwstats_command_proto_depIdxs = []int32{
	0, // 0: xray.app.stats.command.UserStat.ips:type_name -> xray.app.stats.command.OnlineIPEntry
	1, // 1: xray.app.stats.command.UserStat.traffic:type_name -> xray.app.stats.command.TrafficUserStat
	2, // 2: xray.app.stats.command.GetUsersStatsResponse.users:type_name -> xray.app.stats.command.UserStat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_xtls_rwstats_command_proto_init() }
func file_internal_xtls_rwstats_command_proto_init() {
	if File_internal_xtls_rwstats_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_xtls_rwstats_command_proto_rawDesc), len(file_internal_xtls_rwstats_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_xtls_rwstats_command_proto_goTypes,
		DependencyIndexes: file_internal_xtls_rwstats_command_proto_depIdxs,
		MessageInfos:      file_internal_xtls_rwstats_command_proto_msgTypes,
	}.Build()
	File_internal_xtls_rwstats_command_proto = out.File
	file_internal_xtls_rwstats_command_proto_goTypes = nil
	file_internal_xtls_rwstats_command_proto_depIdxs = nil
}
