#!/usr/bin/env bash
# Install a pinned rw-core release and verified optional ASN database.
set -euo pipefail

PINNED_XRAY_VERSION="v26.6.27"
PINNED_XRAY_COMMIT="45cf2898ab12e97a55dd8f1f3d78d903340bdc9e"
PINNED_AMD64_SHA256="b3e5902d06d6282fe53cfa2fc426058b9aeaa429b2c812e20887cd47f26d08bf"
PINNED_ARM64_SHA256="13a251379bea366c2cf10363ad71e75734193d401f26f518bf0c25e5c8f8c931"

XRAY_CORE_VERSION="${XRAY_CORE_VERSION:-$PINNED_XRAY_VERSION}"
XRAY_CORE_SHA256="${XRAY_CORE_SHA256:-}"
CUSTOM_CORE_URL="${CUSTOM_CORE_URL:-}"
CUSTOM_CORE_SHA256="${CUSTOM_CORE_SHA256:-}"
NODE_ENV="${NODE_ENV:-/etc/remnanode/node.env}"
XRAY_BIN="${XRAY_BIN:-/usr/local/lib/remnanode/rw-core}"
GEO_DIR="${GEO_DIR:-/usr/local/share/remnanode/xray}"
ASN_DB_URL="${ASN_DB_URL:-}"
ASN_DB_SHA256="${ASN_DB_SHA256:-}"
ASN_DB_PATH="${ASN_DB_PATH:-/usr/local/share/remnanode/asn/asn-prefixes.bin}"
RNL_REPO="${RNL_REPO:-Luxiaba/remnawave-node-lite-go}"
RNL_TAG="${RNL_TAG:-v0.1.0}"
RNL_INSTALL_ASN="${RNL_INSTALL_ASN:-1}"
DRY_RUN=0
TMP_DIR=""
ASN_SOURCE=""
ASN_TRANSACTIONAL=0
INSTALL_ARMED=0

usage() {
  cat <<'EOF'
Usage: install-xray.sh [options]

Options:
  --version VERSION      rw-core release (default: v26.6.27)
  --sha256 HEX           required when VERSION is not the pinned release
  --dry-run              print actions without changing the system
  --help                 show this help

Environment:
  CUSTOM_CORE_URL        raw custom Linux core binary
  CUSTOM_CORE_SHA256     mandatory SHA-256 for CUSTOM_CORE_URL
  ASN_DB_URL             compact RWASNDB file generated by cmd/asn-builder
  ASN_DB_SHA256          mandatory SHA-256 for ASN_DB_URL
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version) XRAY_CORE_VERSION="${2:-}"; shift 2 ;;
    --sha256) XRAY_CORE_SHA256="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

require_root() {
  if [ "$DRY_RUN" -eq 0 ] && [ "$(id -u)" -ne 0 ]; then
    echo "run as root: sudo bash install-xray.sh" >&2
    exit 1
  fi
}

load_env_var() {
  local key="$1" file="$2" line value
  [ -z "${!key:-}" ] || return 0
  [ -f "$file" ] || return 0
  line="$(grep -E "^[[:space:]]*${key}=" "$file" 2>/dev/null | head -n 1 || true)"
  [ -n "$line" ] || return 0
  value="${line#*=}"
  value="$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")"
  [ -n "$value" ] || return 0
  printf -v "$key" '%s' "$value"
}

download_file() {
  local url="$1" output="$2"
  if command -v curl >/dev/null 2>&1; then
    curl --fail --location --silent --show-error \
      --proto '=https' --tlsv1.2 --retry 3 --retry-all-errors \
      "$url" --output "$output"
    return
  fi
  if command -v wget >/dev/null 2>&1; then
    wget --https-only --tries=3 --output-document="$output" "$url"
    return
  fi
  echo "curl or wget is required" >&2
  return 1
}

verify_sha256() {
  local file="$1" expected="$2" actual
  if ! [[ "$expected" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "invalid SHA-256 for $file" >&2
    return 1
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "$file" | awk '{print $1}')"
  else
    actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  fi
  if [ "${actual,,}" != "${expected,,}" ]; then
    echo "SHA-256 mismatch for $file: got $actual, want $expected" >&2
    return 1
  fi
}

atomic_install() {
  local source="$1" target="$2" mode="$3" staged
  install -d -o root -g root -m 0755 "$(dirname "$target")"
  staged="${target}.new.$$"
  rm -f "$staged"
  if ! install -o root -g root -m "$mode" "$source" "$staged"; then
    rm -f "$staged"
    return 1
  fi
  if ! mv -f "$staged" "$target"; then
    rm -f "$staged"
    return 1
  fi
}

backup_asset() {
  local target="$1" name="$2"
  if [ -e "$target" ] || [ -L "$target" ]; then
    cp -a "$target" "$TMP_DIR/backup/$name"
  else
    : >"$TMP_DIR/backup/$name.absent"
  fi
}

restore_asset() {
  local name="$1" target="$2"
  rm -f "$target" "${target}.new.$$"
  if [ -e "$TMP_DIR/backup/$name" ] || [ -L "$TMP_DIR/backup/$name" ]; then
    install -d -o root -g root -m 0755 "$(dirname "$target")"
    cp -a "$TMP_DIR/backup/$name" "$target"
  elif [ -f "$TMP_DIR/backup/$name.absent" ]; then
    return 0
  else
    echo "missing rollback record for $target" >&2
    return 1
  fi
}

begin_asset_transaction() {
  mkdir -p "$TMP_DIR/backup"
  backup_asset "$XRAY_BIN" rw-core
  backup_asset "$GEO_DIR/geoip.dat" geoip.dat
  backup_asset "$GEO_DIR/geosite.dat" geosite.dat
  if [ -n "$ASN_SOURCE" ]; then
    backup_asset "$ASN_DB_PATH" asn-prefixes.bin
    ASN_TRANSACTIONAL=1
  fi
  INSTALL_ARMED=1
}

rollback_asset_transaction() {
  local failed=0
  echo "rw-core installation failed; restoring previous assets" >&2
  restore_asset rw-core "$XRAY_BIN" || failed=1
  restore_asset geoip.dat "$GEO_DIR/geoip.dat" || failed=1
  restore_asset geosite.dat "$GEO_DIR/geosite.dat" || failed=1
  if [ "$ASN_TRANSACTIONAL" -eq 1 ]; then
    restore_asset asn-prefixes.bin "$ASN_DB_PATH" || failed=1
  fi
  INSTALL_ARMED=0
  [ "$failed" -eq 0 ]
}

cleanup() {
  local status="$?"
  trap - EXIT
  if [ "$status" -ne 0 ] && [ "$INSTALL_ARMED" -eq 1 ]; then
    if ! rollback_asset_transaction; then
      echo "rw-core rollback was incomplete" >&2
      status=1
    fi
  fi
  [ -z "$TMP_DIR" ] || rm -rf "$TMP_DIR"
  exit "$status"
}

select_xray_asset() {
  local pinned_sha256
  case "$(uname -m)" in
    x86_64|amd64)
      XRAY_ASSET="Xray-linux-64.zip"
      pinned_sha256="$PINNED_AMD64_SHA256"
      ;;
    aarch64|arm64)
      XRAY_ASSET="Xray-linux-arm64-v8a.zip"
      pinned_sha256="$PINNED_ARM64_SHA256"
      ;;
    *) echo "unsupported architecture: $(uname -m)" >&2; return 1 ;;
  esac

  if [ "$XRAY_CORE_VERSION" = "$PINNED_XRAY_VERSION" ]; then
    if [ -n "$XRAY_CORE_SHA256" ] && [ "${XRAY_CORE_SHA256,,}" != "${pinned_sha256,,}" ]; then
      echo "refusing SHA-256 override for pinned rw-core $PINNED_XRAY_VERSION" >&2
      return 1
    fi
    XRAY_CORE_SHA256="$pinned_sha256"
  elif [ -z "$XRAY_CORE_SHA256" ]; then
    echo "--sha256 or XRAY_CORE_SHA256 is required for unpinned rw-core $XRAY_CORE_VERSION" >&2
    return 1
  fi
}

prepare_asn_database() {
  if [ "$RNL_INSTALL_ASN" = "0" ]; then
    echo "RNL_INSTALL_ASN=0; skipping ASN database."
    return 0
  fi
  local default_source=0
  if [ -z "$ASN_DB_URL" ]; then
    ASN_DB_URL="https://github.com/${RNL_REPO}/releases/download/${RNL_TAG}/asn-prefixes.bin"
    default_source=1
  fi
  if [ -z "$ASN_DB_SHA256" ] && [ "$default_source" -eq 1 ]; then
    download_file \
      "https://github.com/${RNL_REPO}/releases/download/${RNL_TAG}/SHA256SUMS" \
      "$TMP_DIR/SHA256SUMS"
    ASN_DB_SHA256="$(awk '$2 == "asn-prefixes.bin" || $2 == "*asn-prefixes.bin" { print $1; exit }' "$TMP_DIR/SHA256SUMS")"
  fi
  if [ -z "$ASN_DB_SHA256" ]; then
    echo "ASN_DB_SHA256 is required with ASN_DB_URL" >&2
    return 1
  fi
  ASN_SOURCE="$TMP_DIR/asn-prefixes.bin"
  download_file "$ASN_DB_URL" "$ASN_SOURCE"
  verify_sha256 "$ASN_SOURCE" "$ASN_DB_SHA256"
  if [ "$(od -An -tx1 -N8 "$ASN_SOURCE" | tr -d ' \n')" != "525741534e444201" ]; then
    echo "ASN database has invalid RWASNDB header" >&2
    return 1
  fi
}

require_root
if ! [[ "$RNL_REPO" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$ ]] \
  || ! [[ "$RNL_TAG" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
  echo "invalid RNL_REPO or RNL_TAG" >&2
  exit 2
fi
if ! [[ "$XRAY_CORE_VERSION" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
  echo "invalid rw-core release version: $XRAY_CORE_VERSION" >&2
  exit 2
fi
for key in CUSTOM_CORE_URL CUSTOM_CORE_SHA256 ASN_DB_URL ASN_DB_SHA256; do
  load_env_var "$key" "$NODE_ENV"
done
select_xray_asset
if ! [[ "$XRAY_CORE_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
  echo "XRAY_CORE_SHA256 must be 64 hexadecimal characters" >&2
  exit 2
fi
if [ -n "$CUSTOM_CORE_URL" ]; then
  case "$CUSTOM_CORE_URL" in https://*) ;; *) echo "CUSTOM_CORE_URL must use HTTPS" >&2; exit 2 ;; esac
  if ! [[ "$CUSTOM_CORE_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "CUSTOM_CORE_SHA256 is required with CUSTOM_CORE_URL" >&2
    exit 2
  fi
fi
if [ -n "$ASN_DB_URL" ]; then
  case "$ASN_DB_URL" in https://*) ;; *) echo "ASN_DB_URL must use HTTPS" >&2; exit 2 ;; esac
  if ! [[ "$ASN_DB_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "ASN_DB_SHA256 is required with ASN_DB_URL" >&2
    exit 2
  fi
fi

XRAY_URL="https://github.com/XTLS/Xray-core/releases/download/${XRAY_CORE_VERSION}/${XRAY_ASSET}"
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] download and verify ${XRAY_URL}"
  echo "[dry-run] install rw-core to ${XRAY_BIN} and geo assets to ${GEO_DIR}"
  if [ -n "$CUSTOM_CORE_URL" ]; then
    echo "[dry-run] replace rw-core from verified CUSTOM_CORE_URL"
  fi
  if [ "$RNL_INSTALL_ASN" != "0" ]; then
    echo "[dry-run] install verified ASN database to ${ASN_DB_PATH}"
  fi
  exit 0
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "unzip is required" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap cleanup EXIT

download_file "$XRAY_URL" "$TMP_DIR/xray.zip"
verify_sha256 "$TMP_DIR/xray.zip" "$XRAY_CORE_SHA256"
for item in xray geoip.dat geosite.dat; do
  unzip -p "$TMP_DIR/xray.zip" "$item" >"$TMP_DIR/$item"
  [ -s "$TMP_DIR/$item" ] || { echo "missing $item in verified archive" >&2; exit 1; }
done

if [ -n "$CUSTOM_CORE_URL" ]; then
  if [ -z "$CUSTOM_CORE_SHA256" ]; then
    echo "CUSTOM_CORE_SHA256 is required with CUSTOM_CORE_URL" >&2
    exit 1
  fi
  download_file "$CUSTOM_CORE_URL" "$TMP_DIR/custom-core"
  verify_sha256 "$TMP_DIR/custom-core" "$CUSTOM_CORE_SHA256"
  mv "$TMP_DIR/custom-core" "$TMP_DIR/xray"
fi

chmod 0755 "$TMP_DIR/xray"
CORE_VERSION_OUTPUT="$("$TMP_DIR/xray" version)"
[ -n "$CORE_VERSION_OUTPUT" ] || { echo "rw-core version self-check returned no output" >&2; exit 1; }
prepare_asn_database

begin_asset_transaction
atomic_install "$TMP_DIR/xray" "$XRAY_BIN" 0755
atomic_install "$TMP_DIR/geoip.dat" "$GEO_DIR/geoip.dat" 0644
atomic_install "$TMP_DIR/geosite.dat" "$GEO_DIR/geosite.dat" 0644
if [ -n "$ASN_SOURCE" ]; then
  atomic_install "$ASN_SOURCE" "$ASN_DB_PATH" 0644
fi
"$XRAY_BIN" version >/dev/null
INSTALL_ARMED=0
if [ -n "$ASN_SOURCE" ]; then
  echo "ASN database installed: $ASN_DB_PATH"
fi

if [ "$XRAY_CORE_VERSION" = "$PINNED_XRAY_VERSION" ]; then
  echo "rw-core asset: ${XRAY_CORE_VERSION}@${PINNED_XRAY_COMMIT} (${XRAY_ASSET})"
else
  echo "rw-core asset: ${XRAY_CORE_VERSION} (${XRAY_ASSET})"
fi
printf '%s\n' "$CORE_VERSION_OUTPUT" | sed -n '1p'
echo "rw-core installation complete."
